import "./globals.css";
import { Inter, Noto_Serif } from "next/font/google";

import Navbar from "@/app/Components/Navbar";
import Footer from "./Components/Footer";

const inter = Inter({ subsets: ["latin"] });

const noto_serif = Noto_Serif({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-noto-serif",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${noto_serif.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
